### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters

### ISSUE THREAD

**Issue by ghost** [ihebski/LinksF1nd3r#4]
@ihebski 
My guess is that you next to set utf-8 as default instead of ascii

example:
```
python linksF1nd3r.py https://github.com/zbyuan/pruning_yolov3
```

error:
```
[21:18:48] - [ ! ] - 
[21:18:48] - [ ! ] - /join?source_repo=zbyuan%2Fpruning_yolov3
Traceback (most recent call last):
  File "linksF1nd3r.py", line 123, in <module>
    start(sys.argv[1:])
  File "linksF1nd3r.py", line 66, in start
    report(url)	
  File "linksF1nd3r.py", line 114, in report
    print Fore.GREEN+"[{time}] - [ ! ] - {mylink}".format(mylink=link,time=time.strftime("%H:%M:%S"))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-2: ordinal not in range(128)
```

**Comment by deepseek** [comment]
merge utf-8 https://github.com/ihebski/LinksF1nd3r/pull/5

**Comment by ghost** [comment]
solved
