### ISSUE TITLE
Please Help file error line 121, in <module> start(sys.argv[1:]) 

### ISSUE THREAD

**Issue by HustlazHub** [ihebski/LinksF1nd3r#9]
I have updated all the requirements.txt to use with python3 now I'm having trouble with

 line 121, in <module>
    start(sys.argv[1:]) 

Can you please help me amend the following errors so I can actually use the program????

****************************
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/LinksF1nd3r/linksF1nd3r.py", line 121, in <module>
    start(sys.argv[1:])
  File "/data/data/com.termux/files/home/LinksF1nd3r/linksF1nd3r.py", line 67, in start
    report(url)
    ^^^^^^^^^^^
  File "/data/data/com.termux/files/home/LinksF1nd3r/linksF1nd3r.py", line 97, in report
    links = serchLinks(url)
            ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/LinksF1nd3r/linksF1nd3r.py", line 75, in serchLinks
    website = urllib.request.urlopen(url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
***************************

![Screenshot_2024-01-28-12-42-48-603](https://github.com/ihebski/LinksF1nd3r/assets/145844225/97dc8372-98f0-4407-953c-c21101dddf8b)

**Comment by HustlazHub** [comment]
![Uploading Screenshot_2024-01-28-12-43-10-931.jpg…]()

**Comment by HustlazHub** [comment]
![Screenshot_2024-01-28-12-43-10-931](https://github.com/ihebski/LinksF1nd3r/assets/145844225/cb2054e1-2cdf-496a-a039-cf9cc15ebd3e)

**Comment by HustlazHub** [comment]
![Screenshot_2024-01-28-12-43-34-131](https://github.com/ihebski/LinksF1nd3r/assets/145844225/697a5bba-24ea-4f5a-87e8-3f6ed114c5ef)

**Comment by HustlazHub** [comment]
![Screenshot_2024-01-28-12-57-59-681](https://github.com/ihebski/LinksF1nd3r/assets/145844225/d1f13834-b326-4555-8411-4995b267a616)
